trigger:
- master

pool:
  vmImage: 'ubuntu-latest' # Hosted Ubuntu 1604
  demands: maven


stages:
- stage: BuildWebapp123
  displayName: Buildappmaven1
  jobs:
    - job: buildusingmaven 
      steps:

      - task: Maven@4
        inputs:
          mavenPomFile: 'app/pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: '**/*.jar'
          TargetFolder: '$(build.artifactstagingdirectory)'
        condition: succeededOrFailed()


      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      condition: succeededOrFailed()


- stage: DevDeployment123 
  displayName: Devenv1
  jobs:
  - job: devwebappdeployment
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        itemPattern: '**/*.jar'
        downloadPath: '$(system.defaultworkingdirectory)'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Free Trial(50943cf1-f86f-411b-9120-6eea96d16f3e)'
        appType: 'webAppLinux'
        WebAppName: 'deployment-slot-app-service'
        deployToSlotOrASE: true
        ResourceGroupName: 'vm-rg-third'
        SlotName: 'dev'
        packageForLinux: '$(system.defaultworkingdirectory)/drop/*/target/*.jar'


- stage: UatDeployment123 
  jobs:
  - job: UatWebAppDeployment
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        itemPattern: '**/*.jar'
        downloadPath: '$(system.defaultworkingdirectory)'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Free Trial(50943cf1-f86f-411b-9120-6eea96d16f3e)'
        appType: 'webAppLinux'
        WebAppName: 'deployment-slot-app-service'
        deployToSlotOrASE: true
        ResourceGroupName: 'vm-rg-third'
        SlotName: 'uat'
        packageForLinux: '$(system.defaultworkingdirectory)/drop/*/target/*.jar'

- stage: PreProdEnv
  jobs:
  - deployment: PreProdDeployment 
    environment: 'PreProd'
    strategy:
     runOnce:
      deploy:
       steps:

        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            itemPattern: '**/*.jar'
            downloadPath: '$(system.defaultworkingdirectory)'
            checkDownloadedFiles: true
            extractTars: false

        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Free Trial(50943cf1-f86f-411b-9120-6eea96d16f3e)'
            appType: 'webApp'
            WebAppName: 'deployment-slot-app-service'
            deployToSlotOrASE: true
            ResourceGroupName: 'vm-rg-third'
            SlotName: 'prod'
            packageForLinux: '$(system.defaultworkingdirectory)/drop/*/target/*.jar'




