trigger:
- master

pool:
  vmImage: 'ubuntu-latest' # Hosted Ubuntu 1604
  demands: maven


stages:
- stage: Build_Webapp
  displayName: Build-app-maven
  jobs:
    - job: build-using-maven 
      steps:

      - task: Maven@4
        inputs:
          mavenPomFile: 'app/pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: '**/*.jar'
          TargetFolder: '$(build.artifactstagingdirectory)'
        condition: succeededOrFailed()


      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      condition: succeededOrFailed()


- stage: Dev_Deployment 
  displayName: Dev-env
  jobs:
  - job: dev-webapp-deployment
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        itemPattern: '**/*.jar'
        downloadPath: '$(system.defaultworkingdirectory)'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Free Trial(50943cf1-f86f-411b-9120-6eea96d16f3e)'
        appType: 'webAppLinux'
        WebAppName: 'devvv'
        packageForLinux: '$(System.DefaultWorkingDirectory)drop/**/target/*.jar'